"""ADF node types for building Atlassian Document Format documents."""

from jira_tool.document.nodes.base import Mark, Node
from jira_tool.document.nodes.block import (
    Blockquote,
    BulletList,
    CodeBlock,
    Document,
    Expand,
    Heading,
    ListItem,
    Media,
    MediaGroup,
    MediaSingle,
    NestedExpand,
    OrderedList,
    Panel,
    Paragraph,
    Rule,
    Table,
    TableCell,
    TableHeader,
    TableRow,
)
from jira_tool.document.nodes.inline import (
    Date,
    Emoji,
    HardBreak,
    InlineCard,
    Mention,
    Status,
    Text,
)
from jira_tool.document.nodes.marks import (
    BackgroundColor,
    Code,
    Em,
    Link,
    Strike,
    Strong,
    Subsup,
    TextColor,
    Underline,
)

__all__ = [
    # Base
    "Node",
    "Mark",
    # Block nodes
    "Blockquote",
    "BulletList",
    "CodeBlock",
    "Document",
    "Expand",
    "Heading",
    "ListItem",
    "Media",
    "MediaGroup",
    "MediaSingle",
    "NestedExpand",
    "OrderedList",
    "Panel",
    "Paragraph",
    "Rule",
    "Table",
    "TableCell",
    "TableHeader",
    "TableRow",
    # Inline nodes
    "Date",
    "Emoji",
    "HardBreak",
    "InlineCard",
    "Mention",
    "Status",
    "Text",
    # Marks
    "BackgroundColor",
    "Code",
    "Em",
    "Link",
    "Strike",
    "Strong",
    "Subsup",
    "TextColor",
    "Underline",
]
